program: src/train_model.py
method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  learning_rate:
    min: 0.0001
    max: 0.01
  optimizer:
    values: ["adam", "sgd"]
  batch_size:
    values: [32, 64, 128, 264]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
